configuration:  
  projectName: seeu-zuul

server:
  port: 8001
  contextPath: /api

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
      - id: user-management
        uri: lb://seeu-user-management
        predicates:
        - Path=/users/**
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG