configuration:  
  projectName: seeu-message

server:
  port: 8080

spring:
  # H2
  h2:
    console:
      enabled: true
    path: /h2
  #Datasource
  jpa:
    database: h2
    datasource:
      driver-class-name: org.h2.Driver

management:
  security:
    enabled: false

# Eureka
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://seeu-eureka:8000/eureka/
    registerWithEureka: true
