configuration:  
  projectName: seeu-gateway

server:
  port: 8001

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
      - id: user-management
        uri: lb://seeu-user-management
        predicates:
        - Path=/api/users/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true