configuration:  
  projectName: seeu-message-management

server:
  port: 0

# Database configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

# Eureka
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
